#!/bin/bash

# Quick reference for Forza Racing League deployment
# This file documents all the commands you need

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     🏁 Forza Racing League - Deployment Quick Reference       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Section 1: GitHub Setup
echo "📋 STEP 1: GITHUB SETUP"
echo "======================="
echo ""
echo "1. Push your code with new files:"
echo "   git add ."
echo "   git commit -m 'Add GitHub Actions and Raspberry Pi deployment'"
echo "   git push origin main"
echo ""
echo "2. Check GitHub Actions build:"
echo "   - Go to: https://github.com/YOUR_USERNAME/ForzaRacing/actions"
echo "   - Watch: 'Build and Push Docker Images' workflow"
echo "   - Wait for both backend and frontend to complete"
echo ""
echo "3. Verify images in GitHub Container Registry:"
echo "   - Go to: https://github.com/YOUR_USERNAME/ForzaRacing/pkgs/container"
echo "   - Should see: backend-latest, frontend-latest"
echo ""

# Section 2: Raspberry Pi
echo ""
echo "📦 STEP 2: RASPBERRY PI DEPLOYMENT"
echo "===================================="
echo ""
echo "Option A - Automated (Recommended):"
echo "   ssh pi@YOUR_PI_IP"
echo "   curl -fsSL https://raw.githubusercontent.com/YOUR_USERNAME/ForzaRacing/main/setup-pi.sh | bash"
echo ""
echo "Option B - Manual:"
echo "   ssh pi@YOUR_PI_IP"
echo "   mkdir ~/forza-racing && cd ~/forza-racing"
echo "   wget https://raw.githubusercontent.com/YOUR_USERNAME/ForzaRacing/main/docker-compose.pi.yml"
echo "   nano .env  # Add your OAuth credentials"
echo "   docker-compose -f docker-compose.pi.yml pull"
echo "   docker-compose -f docker-compose.pi.yml up -d"
echo ""

# Section 3: Access
echo ""
echo "🌐 STEP 3: ACCESS YOUR APP"
echo "=========================="
echo ""
echo "1. Get your Pi's IP address:"
echo "   ssh pi@YOUR_PI_IP"
echo "   hostname -I"
echo ""
echo "2. Open browser:"
echo "   http://YOUR_PI_IP:3000"
echo ""
echo "3. Login with Authentik"
echo "4. Start recording races! 🏎️"
echo ""

# Section 4: Common Commands
echo ""
echo "⚙️  COMMON COMMANDS"
echo "==================="
echo ""
echo "On Raspberry Pi:"
echo "   docker-compose -f docker-compose.pi.yml ps               # Check status"
echo "   docker-compose -f docker-compose.pi.yml logs -f          # View logs"
echo "   docker-compose -f docker-compose.pi.yml pull             # Update images"
echo "   docker-compose -f docker-compose.pi.yml restart          # Restart"
echo "   docker-compose -f docker-compose.pi.yml down             # Stop"
echo ""
echo "On your local machine:"
echo "   docker-compose up                                        # Run locally"
echo "   git push origin main                                     # Trigger GitHub Actions"
echo "   bash build-images.sh                                     # Build locally"
echo ""

# Section 5: Documentation
echo ""
echo "📚 DOCUMENTATION"
echo "================"
echo ""
echo "Setup & OAuth:"
echo "   SETUP.md                           - Docker local setup"
echo "   OAUTH_SETUP.md                     - OAuth2 configuration"
echo "   OAUTH_INTEGRATION.md               - Auth details"
echo ""
echo "Raspberry Pi:"
echo "   RASPBERRY_PI_QUICKSTART.md         - 5-minute start"
echo "   RASPBERRY_PI_DEPLOYMENT.md         - Detailed guide"
echo "   RASPBERRY_PI_DEPLOYMENT_SETUP.md   - Complete overview"
echo ""
echo "GitHub & Docker:"
echo "   GITHUB_CONTAINER_REGISTRY.md       - GHCR hosting"
echo ""

# Section 6: Troubleshooting
echo ""
echo "🔧 TROUBLESHOOTING"
echo "=================="
echo ""
echo "If app won't start:"
echo "   1. Check Docker is running: docker ps"
echo "   2. Check logs: docker-compose -f docker-compose.pi.yml logs"
echo "   3. Check .env file is configured"
echo "   4. Verify port 3000 is not in use"
echo ""
echo "If OAuth login fails:"
echo "   1. Check OAUTH_CLIENT_SECRET is correct"
echo "   2. Verify OAUTH_REDIRECT_URI matches Pi's IP"
echo "   3. Ensure Authentik server is accessible"
echo ""
echo "If can't access from another device:"
echo "   1. Get Pi's IP: hostname -I"
echo "   2. Check firewall: sudo ufw status"
echo "   3. Ping Pi: ping RASPBERRY_PI_IP"
echo ""

# Section 7: Next Steps
echo ""
echo "✅ TODO CHECKLIST"
echo "================="
echo ""
echo "Before pushing to GitHub:"
echo "   [ ] Replace YOUR_GITHUB_USERNAME in docker-compose.pi.yml"
echo "   [ ] Update OAUTH_REDIRECT_URI in all .env files"
echo "   [ ] Update repository URLs in QUICKSTART files"
echo ""
echo "After GitHub Actions builds:"
echo "   [ ] Verify images exist in GitHub Packages"
echo "   [ ] Confirm both amd64 and arm64 platforms built"
echo ""
echo "On Raspberry Pi:"
echo "   [ ] SSH access working"
echo "   [ ] Docker installed"
echo "   [ ] .env file configured with OAuth credentials"
echo "   [ ] App accessible at http://PI_IP:3000"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "                  Ready to deploy! 🚀"
echo "═══════════════════════════════════════════════════════════════"
